### ISSUE TITLE
Start versioning provider with release branches

### ISSUE THREAD

**Issue by furkatgofurov7** [rancher-sandbox/cluster-api-provider-rke2#194]
**Describe the solution you'd like:**
Start versioning the provider following the best practices used in upstream repos (CAPI/CAPI operator and most of the CAPI* providers)

**Why do you want this feature:**
Currently, it is not trivial to decide whether we want to cut minor/patch releases since all the development is carried out on the main branch, and things like backporting patches/bug fixes and releasing a new version of the provider, and working on breaking changes at the same time is impossible. For that reason, we can introduce a release branches strategy in the provider, where we will be branching out of the main branch to the release-X branch when doing the minor releases, and cut all the upcoming patch releases from that same release-X branch.

**Anything else you would like to add:**
Related to: https://github.com/rancher-sandbox/cluster-api-provider-rke2/issues/169

**Comment by alexander-demicev** [comment]
I created a release branch https://github.com/rancher-sandbox/cluster-api-provider-rke2/tree/release-0.2, we should also document the release process as in https://github.com/kubernetes-sigs/cluster-api-operator/blob/main/docs/release.md

**Comment by richardcase** [comment]
As @alexander-demicev says, wewe need to document this as part of the release process.
