### ISSUE TITLE
Dynamically download RKE2 artifacts from container image avoiding RKE2 version-specific node images

### ISSUE THREAD

**Issue by ron1** [rancher-sandbox/cluster-api-provider-rke2#220]
**Describe the solution you'd like:**

CAPI node images typically have bootstrapping dependencies baked in. It seems CABPR has embraced this approach and currently requires that RKE2 version-specific artifacts be baked into its node images.

OTOH, folks like myself that are currently using the Rancher v2 provisioner with RKE2 are not accustomed to maintaining node images for each specific RKE2 version. For those users, migrating to CAPI/CABPR will require extra work managing RKE2 version-specific node images. Extra storage will also be required since each image itself will be significantly larger and the number of images being maintained will increase.

Consider enhancing CABPR to support the dynamic downloading of RKE2 artifacts from container images to avoid the need to build RKE2 version-specific node images. 

One approach to solving this problem might directly use the RKE2 versioned container images already being published at url: https://hub.docker.com/r/rancher/system-agent-installer-rke2 that embed the necessary RKE2 versioned install artifacts described at url: https://github.com/rancher/system-agent-installer-rke2/blob/2fda2b4b6d8553ebfed329c72ad0f85174d7b9a2/scripts/download#L13-L23. The `crane` binary or its library could be used to download and extract the RKE2 artifacts.

**Why do you want this feature:**

As a user looking to migrate from deploying RKE2 via the Rancher v2 Provisioner to deploying RKE2 via CABPR, I should not be forced to change the process I currently use for managing node images.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

This feature seems like a nice CABPR ease-of-use value-add over its primary competitor, the kubeadm bootstrap provider.

**Comment by alexander-demicev** [comment]
The current bootstrap mechanism allows using almost any node image for all RKE2 version. RKE2 is downloaded on the host using an installation script that is passed through the userdata. We're going to continue support this option. In future we will also introduce in-place updates of machines https://hackmd.io/Wv_u2xXJQsaj4wWFQ3PqCQ?edit

**Comment by alexander-demicev** [comment]
I closed this issue since we already allow using one node image for many RKE2 versions and will not remove this for feature parity with v2prov
