### ISSUE TITLE
Refactor how version is passed to the specification 

### ISSUE THREAD

**Issue by salasberryfin** [rancher-sandbox/cluster-api-provider-rke2#229]
**Describe the solution you'd like:**

Adding support for `ClusterClass` required implementing extra fields in [RKE2ControlPlaneSpec](https://github.com/rancher-sandbox/cluster-api-provider-rke2/blob/4ecd6869a1e74e6cb0aeeab06ff454ba6221b550/controlplane/api/v1alpha1/rke2controlplane_types.go#L39):
- Version
- MachineTemplate

While these fields have been implemented (as placeholders) to allow using `RKE2ControlPlaneTemplate` and create clusters using `ClusterClass` in this [PR](https://github.com/rancher-sandbox/cluster-api-provider-rke2/pull/226), `Version` is currently **only** being configured in [RKE2AgentConfig](https://github.com/rancher-sandbox/cluster-api-provider-rke2/blob/4ecd6869a1e74e6cb0aeeab06ff454ba6221b550/bootstrap/api/v1alpha1/rke2config_types.go#L62).

Following up on the `ClusterClass` work, version fields must be managed so that:
- Only one of the two fields is used: an error should be raised if both are set.
- Take the value from the non-empty version field.

In a future API version, the current `RKE2AgentConfig.Version` should be deprecated in favor of `RKE2ControlPlaneSpec.Version`.

**Why do you want this feature:**

As stated in the original `ClusterClass` proposal [here](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20210526-cluster-class-and-managed-topologies.md#provider-implementation), Control Plane providers must support these fields in the specification.

**Anything else you would like to add:**

**Comment by Danil-Grigorev** [comment]
I believe it was implemented in #313 and #306, with old agentConfig.Version converted to `RKE2ControlPlane`version, fulfilling upstream contract.
