### ISSUE TITLE
RKE2 registration token inconsistency between 1st CP and following nodes 

### ISSUE THREAD

**Issue by richardcase** [rancher-sandbox/cluster-api-provider-rke2#233]
**What happened:**

When using CAPRKE2 with CAPO there is an issue where the registration token on the 1st CP machine differs to that of the following CP machine or the worker machines. This results in a failure to join the new nodes to cluster with a 401 not authorised

**What did you expect to happen:**
Expectation is that the nodes are able to join the cluster with the correct token.

**How to reproduce it:**

**Anything else you would like to add:**

See [sylva downstream issue](https://gitlab.com/sylva-projects/sylva-core/-/issues/832) for more detail.

**Environment:**

- rke provider version:
- OS (e.g. from `/etc/os-release`):

**Comment by zioc** [comment]
I've digged a bit into the issue and added some details in downstream issue: https://gitlab.com/sylva-projects/sylva-core/-/issues/832#note_1719613588

Hopefully the fix should be quite simple, we could just ensure that token's secret doesn't already exists prior to create a new one.

**Comment by richardcase** [comment]
Looking at the code suggested by @zioc , this appears to be the problem.

**Comment by richardcase** [comment]
Testing with CAPD i can see that sometimes we see 2 server token generated messages (i added the token to see what the value was for testing):

```
I0109 14:53:54.364793      21 rke2config_controller.go:344]  "msg"="RKE2 server token generated and stored in Secret!" "Machine"="default/test1-control-plane-pwvm7" "RKE2Config"={"name":"test1-control-plane-wnhnt","namespace":"default"} "cluster-name"="test1" "controller"="rke2config" "controllerGroup"="bootstrap.cluster.x-k8s.io" "controllerKind"="RKE2Config" "name"="test1-control-plane-wnhnt" "namespace"="default" "reconcileID"="a5f3c5a4-21f9-493e-b702-52eec751f000" "resourceVersion"="1513" "token"="9cad8e2489a851056ee2b6277c3a3207"
I0109 14:53:54.427354      21 rke2config_controller.go:344]  "msg"="RKE2 server token generated and stored in Secret!" "Machine"="default/test1-control-plane-pwvm7" "RKE2Config"={"name":"test1-control-plane-wnhnt","namespace":"default"} "cluster-name"="test1" "controller"="rke2config" "controllerGroup"="bootstrap.cluster.x-k8s.io" "controllerKind"="RKE2Config" "name"="test1-control-plane-wnhnt" "namespace"="default" "reconcileID"="e566b9d6-03f6-4efa-9acb-c9f8bddf4e76" "resourceVersion"="1522" "token"="91c48ec51481f1a2dc38f7d970ac9826"
```

**Comment by tmmorin** [comment]
hey @richardcase 

we were wondering if you would have an idea of when a fix would be available

the issue is a repeat offender in Sylva project CI jobs

please don't hesitate to reach out if any testing of a candidate fix would help -- although the issue from a bird view look possibly straightforward to fix/validate

thanks in advance :)
