### ISSUE TITLE
[e2e] Test have been failing for a long time

### ISSUE THREAD

**Issue by richardcase** [rancher-sandbox/cluster-api-provider-rke2#242]
**What happened:**
Our nightly e2e test have been failing for a long time now.

**What did you expect to happen:**
The tests to pass consistently

**How to reproduce it:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- rke provider version:
- OS (e.g. from `/etc/os-release`):

**Comment by Danil-Grigorev** [comment]
Also, https://github.com/kubernetes-sigs/cluster-api/pull/9952 seems to be required here too.

**Comment by Danil-Grigorev** [comment]
@richardcase I think this was closed by mistake. e2e tests are not passing with this merged change alone.

**Comment by richardcase** [comment]
They passed for me this morning

**Comment by Danil-Grigorev** [comment]
@furkatgofurov7 You mentioned there is an issue with the e2e tests, later in the run. Can you give more details? I’ll retry on my side as well. In my setup I was hitting originally this issue: https://github.com/rancher-sandbox/cluster-api-provider-rke2/issues/263

**Comment by richardcase** [comment]
Maybe this is now hinting an environmental factors. I will run it in different environments to check.

I also created #267 so we can run the e2e via self hosted runners,

**Comment by furkatgofurov7** [comment]
> @furkatgofurov7 You mentioned there is an issue with the e2e tests, later in the run. Can you give more details? I’ll retry on my side as well. In my setup I was hitting originally this issue: #263

It was running in my fork, re-running it again to test the latest changes https://github.com/furkatgofurov7/cluster-api-provider-rke2/actions/runs/7958544104/job/21723628664

**Comment by Danil-Grigorev** [comment]
I see the job is passing green. It looks like it is environment specific in some way: https://github.com/rancher-sandbox/cluster-api-provider-rke2/actions/runs/7958280349

**Comment by furkatgofurov7** [comment]
> > @furkatgofurov7 You mentioned there is an issue with the e2e tests, later in the run. Can you give more details? I’ll retry on my side as well. In my setup I was hitting originally this issue: #263
> 
> It was running in my fork, re-running it again to test the latest changes https://github.com/furkatgofurov7/cluster-api-provider-rke2/actions/runs/7958544104/job/21723628664

Passed in my fork: https://github.com/furkatgofurov7/cluster-api-provider-rke2/actions/runs/7958544104

**Comment by Danil-Grigorev** [comment]
Yes, it passed for me as well. There was a change I overlooked - [changed](https://github.com/rancher-sandbox/cluster-api-provider-rke2/pull/260/commits/7177130637b5dc051eed4d3d3185395ec806f6bc) number of nodes from 1 to 3. This corresponds with a workaround for the bug intended to be fixed #263 and thus e2e does not hit the problem anymore.
