### ISSUE TITLE
Installation with ignition can fail with a misleading error

### ISSUE THREAD

**Issue by hardys** [rancher-sandbox/cluster-api-provider-rke2#276]
**What happened:**
When deploying on SLEMicro with ignition I hit an error like this coming from `rke2-install.service`

```
+ semanage fcontext -a -t systemd_unit_file_t /usr/lib/systemd/system/rke2-server.service
ValueError: File context for /usr/lib/systemd/system/rke2-server.service already defined
```

This is misleading as ` /usr/lib/systemd/system/rke2-server.service` doesn't actually exist - initially I suspected an selinux issue, but the problem happens earlier, the script looks like:

```
cat /etc/rke2-install.sh 
#!/bin/bash
set -e

curl -sfL https://get.rke2.io/ | INSTALL_RKE2_VERSION=v1.25.3+rke2r1 sh -s - server
semanage fcontext -a -t systemd_unit_file_t  /usr/lib/systemd/system/rke2-server.service
setenforce 0
systemctl enable rke2-server.service
systemctl start rke2-server.service
restorecon /etc/systemd/system/rke2-server.service
mkdir -p /run/cluster-api && echo success > /run/cluster-api/bootstrap-success.complete
setenforce 1
```

Because we don't set `pipefail` if anything causes the curl to fail, we silently ignore it and see the semanage error previously mentioned instead.

**What did you expect to happen:**
If the curl download fails, we should surface that error so the root cause can be addressed (in my case it was a network configuration issue)

Probably we should either set `pipefail` in the script, or split the `curl` and running the script into two steps

**How to reproduce it:**
Deploy in any environment where the connection to `https://get.rke2.io/` is somehow broken so the `curl` fails

**Environment:**

- rke provider version: 0.2.4
- OS (e.g. from `/etc/os-release`): SLEMicro 5.5

**Comment by alknopfler** [comment]
agree @hardys

**Comment by mchiappero** [comment]
I have managed to reproduce the issue with both the original container installed by the metal3-demo scripts/playbooks and with the updated one that doesn't hide the source error:

```
controlplane-0:~ # systemctl status rke2-install.service
× rke2-install.service - rke2-install
     Loaded: loaded (/etc/systemd/system/rke2-install.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2024-04-16 08:28:39 UTC; 1min 25s ago
    Process: 2198 ExecStart=/etc/rke2-install.sh (code=exited, status=35)
   Main PID: 2198 (code=exited, status=35)

Apr 16 08:28:48 controlplane-0 systemd[1]: Starting rke2-install...
Apr 16 08:28:39 controlplane-0 systemd[1]: rke2-install.service: Main process exited, code=exited, status=35/n/a
Apr 16 08:28:39 controlplane-0 systemd[1]: rke2-install.service: Failed with result 'exit-code'.
Apr 16 08:28:39 controlplane-0 systemd[1]: Failed to start rke2-install.
```

However the return code from curl is not particularly helpful in determining the root cause of the issue, maybe I'd be better to check the return code from curl and log a message. Any preference?
