### ISSUE TITLE
in airGapped mode, ensure that the desired k8s version is used

### ISSUE THREAD

**Issue by tmmorin** [rancher-sandbox/cluster-api-provider-rke2#297]
We noticed [while developing Sylva](https://gitlab.com/sylva-projects/sylva-core/-/issues/1081) that, in airGapped mode (`spec.agentConfig.airGapped: true`), the combination of RKE2 bootstrap provider  and RK2 itself will result in using _whatever version of RKE2 is present in `/opt/rke2-artifacts`, even if this version does not match `spec.agentConfig.version`.

It creates a risk of unintendedly using an undesired version, and possibly unintendedly upgrading or downgrading, if the OS image is not selected carefully.

A safer behavior for air-gapped mode would be to abort RKE2 installation if the RKE2 version that can be found on disk does not match `spec.agentConfig.version`.

/cc @richardcase

**Comment by richardcase** [comment]
Thank you @tmmorin
