### ISSUE TITLE
Add upgrade test

### ISSUE THREAD

**Issue by richardcase** [rancher-sandbox/cluster-api-provider-rke2#308]
We are changing the logic in relation to **version** in the **v1beta1** release (specifically in #306). As a result we need to add a test to ensure that we don't break existing users of the provider.

The test should use an example from an existing user.

**Comment by Danil-Grigorev** [comment]
I believe it was done in https://github.com/rancher-sandbox/cluster-api-provider-rke2/pull/313 and couple PRs prior in [upgrade e2e](https://github.com/rancher-sandbox/cluster-api-provider-rke2/blob/main/test/e2e/e2e_upgrade_test.go ). This test is complex for a reason, as it tests multiple aspects of API version bump, version conversion and scalability before/after the upgrade. The complexity was mostly added to replicate edge case scenarios with different customer environments.
