### ISSUE TITLE
Create an Ubuntu docker image with all pre-requisites for RKE2 Air-Gapped installation

### ISSUE THREAD

**Issue by belgaied2** [rancher-sandbox/cluster-api-provider-rke2#34]
**Describe the solution you'd like:**
The air-gapped mode for installing RKE2 will first rely on OS images that contains RKE2 pre-requisites for installing correctly.
We need to create that image for CAPD and document where RKE2 files are located.

**Why do you want this feature:**
For the Air-Gapped mode, bundling the RKE2 binary assets is necessary. This is needed in order to be able to test the provider in air-gapped mode with CAPD.

**Anything else you would like to add:**
Needed for Air-Gapped but depending on the implementation, this might be the only way to go.

**Comment by richardcase** [comment]
Related to #24
