### ISSUE TITLE
Implement first working Bootstrap Controller

### ISSUE THREAD

**Issue by belgaied2** [rancher-sandbox/cluster-api-provider-rke2#36]
As a step to implementing the bootstrap controller, it would be good to create a first working draft with minimal functionality (without all api fields and without customization), just standard RKE2 install with all the defaults.

This might be done by implementing the following, fairly independent tasks:
- [x] #39
- [x] #40
- [ ] #41
- [x] #42
- [x] #43
- [x] #44

**Comment by belgaied2** [comment]
Fixed in f426825fc2c51e12ae34f9748bdd0a5266651820

**Comment by richardcase** [comment]
Very similar to #25. Should we close #25?

**Comment by belgaied2** [comment]
Well, I thought this as a first MVP (most API fields do nothing because their logic would not exist) and the #25 as a fully functional one with all the planned features.

**Comment by richardcase** [comment]
Good thinking 👍

**Comment by belgaied2** [comment]
Implemented by #60
