### ISSUE TITLE
Add ClusterClass support

### ISSUE THREAD

**Issue by richardcase** [rancher-sandbox/cluster-api-provider-rke2#75]
**Describe the solution you'd like:**
I'd like to be able to use ClusterClass with the RKE2 provider.

**Why do you want this feature:**
I am want to create instances of a class that uses the RKE2 controlplane and bootstrap providers.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by salasberryfin** [comment]
After discussion with @richardcase & @furkatgofurov7, I will work on this.

**Comment by ThomasVitale** [comment]
@salasberryfin should the "stale" label be removed?

**Comment by salasberryfin** [comment]
@ThomasVitale I haven't been able to spend time on this. I'll delete my assignment in case someone is willing to work on this and come back later to it if it's still open.

**Comment by salasberryfin** [comment]
There's an upstream PR https://github.com/kubernetes-sigs/cluster-api/pull/9952 that has been merged but we're waiting for it to be release before merging this.

**Comment by salasberryfin** [comment]
- The upstream issue that's currently blocking this from being merged is expected to be released in `cluster-api:v1.7` (~april). Not having this functionality in core CAPI means that the provisioning of Docker machines might fail intermittently but, after discussing with the team, we consider that this shouldn't prevent us from having this supported in CAPRKE2.
- As `cluster-api-provider-rke2` is now at version `v1beta1`, the support for Cluster Class must be migrated to the new API version.
