### ISSUE TITLE
Provide an API option to pass any cloudinit parameter.

### ISSUE THREAD

**Issue by zioc** [rancher-sandbox/cluster-api-provider-rke2#78]
**Describe the solution you'd like:**

cloud-init has a many features, and it would be painfull (and wouldn't add much value) to map each of these feature options in bootstrap provider API.

For example, RKE2 boostrap provider already supports File injection, and NTP support is planned. Kubeadm also supports disk-setup (which [would be also be desirable for this provider](https://github.com/rancher-sandbox/cluster-api-provider-rke2/issues/77)) and user-definitions. In bootstrap providers, these values are often passed as is to cloud init file, but they require a fair amount of boilerplate code.

The provider could instead propose an untyped option where the user would provide a map of cloud-init instructions. These instruction could be merged with ones that are generated by bootstrap provider ( https://github.com/rancher-sandbox/cluster-api-provider-rke2/issues/68 could help a lot on that front)

For some cloud-init instructions that are used by boostrap provider (like runCmd), there won't be any obvious way to merge them with user-provided ones. In that case, an admission webhook could be used to evict such user values and instruct him to use Pre/PostRKE2Commands instead.

**Comment by belgaied2** [comment]
I am trying to think about implementation about this, and would suggest this:

- We would add a field `addtionalCloudInit` in the `agentConfig` section of an `RKE2Config` object, which is a reference to a configMap containing the cloud-init.
- It looks like we cannot merge easily 2 cloud-init in a robust way, at least inside a cloud-init section like `runcmd`. I suggest automatically ignoring any section that is supposed to be generated by the provider, which are:
   - runcmd
   - ntp
   - write_files
- Any given additionalCloudInit would be stripped off of the above section, and added to the end of the generated cloud-init.

Questions:
- Do you think this approach is acceptable?
- Is it better to expose the cloud-init content directly in the `additionalCloudInit` field? Like inline YAML ?
- What kind of validation is expected? 
- If the given cloud-init configuration is invalid, how should the provider react ? Failure to reconcile or creation without the `additionalCloudConfig` ? I suggest failing.

**Comment by belgaied2** [comment]
After some discussion with @alexander-demicev and @richardcase , it looks like the way you are suggesting, using `runtime.Object` (actually, `runtime.RawExtension` - see [here](https://pkg.go.dev/k8s.io/apimachinery/pkg/runtime#RawExtension)) is not recommended. Manipulating `runtime.RawExtension` is difficult, and hardly brings any benefit in this situation, where we could either have a simple inline YAML or Base64-encoded field.

The the idea is to parse the YAML into a map, then remove the keys `runcmd` , `write_files` and `ntp` (might be subject to change in the future), and remarshal it into a YAML that is added to the final cloud-init. This way we preserve everything other than the above three sections. Any change change to the field should trigger a rollingupgrade, and no validation will be done. The user takes responsibility for troubleshooting through looking at the logs in infrastructure provider pod or on the node.
